name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Publish to folder
      #run: msbuild /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=./published/ /p:PackageAsSingleFile=false
      #run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir=".\published\";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false"
      run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir=".\\published\\";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false"

    - name: List directory
      run: ls -R

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ehbanner00'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_982ae785982749679bbd5c01cbf7b64a }}
        package: ./published/

#    - name: Deploy to Azure WebApp
#      uses: azure/webapps-deploy@v1
#      with:
#        app-name: 'ehbanner00'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_982ae785982749679bbd5c01cbf7b64a }}
#        package: ./published/
